name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Service One -> Validate composer.json and composer.lock
      working-directory: ./service_one
      run: composer validate

    - name: Service One -> Cache Composer packages
      id: composer-cache-1
      uses: actions/cache@v2
      with:
        working-directory: ./service_one
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Service One -> Install dependencies
      working-directory: ./service_one
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Service One -> Run test suite
      working-directory: ./service_one
      run: composer install --prefer-dist --no-progress --no-suggest && composer run-script test

    - name: Service Integrator -> Validate composer.json and composer.lock
      working-directory: ./service_integrator
      run: composer validate

    - name: Service Integrator -> Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        working-directory: ./service_integrator
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Service Integrator -> Install dependencies
      working-directory: ./service_integrator
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Service Integrator -> Run test suite
      working-directory: ./service_integrator
      run: composer install --prefer-dist --no-progress --no-suggest && composer run-script test:unit
